CREATE TABLE `receptor_library` (
	`id` int AUTO_INCREMENT NOT NULL,
	`target_name` varchar(128) NOT NULL,
	`description` text NOT NULL,
	`pdb_id` varchar(16) NOT NULL,
	`pdb_file_name` varchar(255) NOT NULL,
	`pdbqt_file_name` varchar(255) NOT NULL,
	`pdbqt_url` text NOT NULL,
	`pdb_url` text,
	`chain` varchar(4) DEFAULT 'A',
	`ligand_chain` varchar(4),
	`file_size` int,
	`resolution` varchar(16),
	`experimental_method` varchar(64),
	`organism` varchar(255),
	`default_box_center_x` decimal(10,3),
	`default_box_center_y` decimal(10,3),
	`default_box_center_z` decimal(10,3),
	`default_box_size_x` decimal(10,3),
	`default_box_size_y` decimal(10,3),
	`default_box_size_z` decimal(10,3),
	`default_exhaustiveness` int DEFAULT 8,
	`default_num_poses` int DEFAULT 5,
	`category` varchar(64),
	`tags` text,
	`notes` text,
	`source` varchar(128) DEFAULT 'RCSB PDB',
	`uploaded_by` varchar(128),
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `receptor_library_id` PRIMARY KEY(`id`),
	CONSTRAINT `receptor_library_target_name_unique` UNIQUE(`target_name`)
);
