CREATE TABLE `admet_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`analog_id` int NOT NULL,
	`smiles` text NOT NULL,
	`source` varchar(64) NOT NULL DEFAULT 'admet_ai_chemprop',
	`ames` varchar(20),
	`herg` varchar(20),
	`dili` varchar(20),
	`ld50` varchar(20),
	`clintox` varchar(20),
	`bbb_permeability` varchar(20),
	`oral_bioavailability` varchar(20),
	`hia` varchar(20),
	`caco2` varchar(20),
	`pgp` varchar(20),
	`ppbr` varchar(20),
	`half_life` varchar(20),
	`clearance_hepatocyte` varchar(20),
	`cyp1a2` varchar(20),
	`cyp2c9` varchar(20),
	`cyp2c19` varchar(20),
	`cyp2d6` varchar(20),
	`cyp3a4` varchar(20),
	`solubility` varchar(20),
	`lipophilicity` varchar(20),
	`molecular_weight` varchar(20),
	`logp` varchar(20),
	`tpsa` varchar(20),
	`qed` varchar(20),
	`raw_result` json,
	`batch_run_id` varchar(64),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`created_by` int,
	CONSTRAINT `admet_results_id` PRIMARY KEY(`id`)
);
