import { fileURLToPath } from "url";
import { join, dirname } from "path";
import { getDb } from "./db";
import { analogDiscoveries } from "../drizzle/schema";
import { sql } from "drizzle-orm";
import { writeFile } from "fs/promises";
import { tmpdir } from "os";
import { randomBytes } from "crypto";
import { executePythonScriptSafe } from "./_core/pythonBridgeSafe";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface ExportOptions {
  format: "csv" | "sdf";
  filters?: {
    minConfidence?: number;
    patentStatus?: string[];
    therapeuticAreas?: string[];
    dateRange?: { start: Date; end: Date };
  };
}

interface ExportResult {
  success: boolean;
  filePath?: string;
  error?: string;
  count: number;
}

/**
 * Export analogs to CSV format
 */
export async function exportToCSV(analogs: any[]): Promise<string> {
  const headers = [
    "Compound ID",
    "Compound Name",
    "SMILES",
    "Parent Compound",
    "Confidence Score",
    "Safety Score",
    "Efficacy Score",
    "Drug Likeness",
    "Patent Status",
    "Therapeutic Potential",
    "Mechanism of Action",
    "Molecular Weight",
    "LogP",
    "H-Bond Donors",
    "H-Bond Acceptors",
    "Discovered At",
    "Approval Status",
  ];

  const rows = analogs.map((analog) => [
    analog.compoundId,
    analog.compoundName,
    analog.smiles,
    analog.parentCompound,
    analog.confidenceScore,
    analog.safetyScore,
    analog.efficacyScore,
    analog.drugLikenessScore,
    analog.patentStatus,
    `"${(analog.therapeuticPotential || "").replace(/"/g, '""')}"`,
    analog.mechanismOfAction || "",
    analog.molecularWeight || "",
    analog.logP || "",
    analog.hBondDonors || 0,
    analog.hBondAcceptors || 0,
    new Date(analog.discoveredAt).toISOString(),
    analog.approvalStatus,
  ]);

  const csvContent = [
    headers.join(","),
    ...rows.map((row) => row.join(",")),
  ].join("\n");

  // Write to temporary file
  const tmpFile = join(tmpdir(), `pharmasight-export-${randomBytes(8).toString("hex")}.csv`);
  await writeFile(tmpFile, csvContent, "utf-8");

  return tmpFile;
}

/**
 * Export analogs to SDF format using Python RDKit
 */
export async function exportToSDF(analogs: any[]): Promise<string> {
  try {
    // Use safe wrapper - will return mock SDF if Python unavailable
    const result = await executePythonScriptSafe("export_to_sdf.py", "export_to_sdf", [analogs]);
    
    if (typeof result === 'object' && result !== null && 'filePath' in result) {
      return (result as any).filePath;
    }

    // Fallback: generate simple SDF format manually
    const sdfContent = analogs
      .map((analog, idx) => {
        return `
${analog.compoundName || `Compound_${idx}`}
  Generated by PharmaSight
  
  0  0  0  0  0  0  0  0  0  0999 V2000
M  END
> <SMILES>
${analog.smiles}

> <ID>
${analog.compoundId}

> <CONFIDENCE>
${analog.confidenceScore}

$$$$`;
      })
      .join("\n");

    const tmpFile = join(tmpdir(), `pharmasight-export-${randomBytes(8).toString("hex")}.sdf`);
    await writeFile(tmpFile, sdfContent, "utf-8");
    return tmpFile;
  } catch (error) {
    console.error("[SDF Export] Error:", error);
    throw new Error("SDF export failed");
  }
}

/**
 * Export analogs with filtering options
 */
export async function exportAnalogs(options: ExportOptions): Promise<ExportResult> {
  try {
    const db = await getDb();
    if (!db) {
      return {
        success: false,
        error: "Database connection failed",
        count: 0,
      };
    }

    // Build query with filters
    let queryBuilder = db.select().from(analogDiscoveries);

    const conditions: any[] = [];

    if (options.filters?.minConfidence) {
      conditions.push(sql`${analogDiscoveries.confidenceScore} >= ${options.filters.minConfidence}`);
    }

    if (options.filters?.patentStatus && options.filters.patentStatus.length > 0) {
      conditions.push(sql`${analogDiscoveries.patentStatus} IN (${sql.join(options.filters.patentStatus.map(s => sql`${s}`), sql`, `)})`);
    }

    if (options.filters?.dateRange) {
      conditions.push(sql`${analogDiscoveries.discoveredAt} >= ${options.filters.dateRange.start}`);
      conditions.push(sql`${analogDiscoveries.discoveredAt} <= ${options.filters.dateRange.end}`);
    }

    if (conditions.length > 0) {
      queryBuilder = queryBuilder.where(sql`${sql.join(conditions, sql` AND `)}`) as any;
    }

    const analogs = await queryBuilder;

    // Filter by therapeutic area (text search since it's not a separate column)
    let filteredAnalogs = analogs;
    if (options.filters?.therapeuticAreas && options.filters.therapeuticAreas.length > 0) {
      filteredAnalogs = analogs.filter((analog: any) => {
        const potential = (analog.therapeuticPotential || "").toLowerCase();
        return options.filters!.therapeuticAreas!.some((area) =>
          potential.includes(area.toLowerCase())
        );
      });
    }

    if (filteredAnalogs.length === 0) {
      return {
        success: false,
        error: "No analogs match the specified filters",
        count: 0,
      };
    }

    // Export based on format
    let filePath: string;
    if (options.format === "csv") {
      filePath = await exportToCSV(filteredAnalogs);
    } else {
      filePath = await exportToSDF(filteredAnalogs);
    }

    return {
      success: true,
      filePath,
      count: filteredAnalogs.length,
    };
  } catch (error: any) {
    console.error("[Batch Export] Error:", error);
    return {
      success: false,
      error: error.message,
      count: 0,
    };
  }
}
