import { readFile } from "fs/promises";
import { getDb } from "./db";
import { analogDiscoveries } from "../drizzle/schema";

/**
 * Import autonomous discoveries from pharmasight-platform
 * Reads from the autonomous_discoveries.json file generated by the research engine
 */

const DISCOVERIES_PATH = "/home/ubuntu/pharmasight-platform/data/autonomous_discoveries.json";

interface AutonomousDiscovery {
  compound_id: string;
  compound_name: string;
  parent_compound: string;
  smiles: string;
  confidence_score: number;
  safety_score: number;
  efficacy_score: number;
  similarity_score: number;
  patent_status: string;
  market_value: string;
  therapeutic_potential: string;
  key_differences: string;
  discovered_at: string;
}

export async function importAutonomousDiscoveries(): Promise<{
  success: boolean;
  importedCount: number;
  error?: string;
}> {
  try {
    // Read the autonomous discoveries file
    const fileContent = await readFile(DISCOVERIES_PATH, "utf-8");
    const discoveries: AutonomousDiscovery[] = JSON.parse(fileContent);

    if (!Array.isArray(discoveries) || discoveries.length === 0) {
      return {
        success: true,
        importedCount: 0,
      };
    }

    const db = await getDb();
    if (!db) {
      return {
        success: false,
        importedCount: 0,
        error: "Database not available",
      };
    }

    let importedCount = 0;

    // Import each discovery
    for (const discovery of discoveries) {
      try {
        // Check if already exists
        const existing = await db
          .select()
          .from(analogDiscoveries)
          .where((fields: any) => fields.compoundId.eq(discovery.compound_id))
          .limit(1);

        if (existing.length > 0) {
          continue; // Skip if already imported
        }

        // Insert new discovery
        await db.insert(analogDiscoveries).values({
          compoundId: discovery.compound_id,
          compoundName: discovery.compound_name,
          parentCompound: discovery.parent_compound,
          smiles: discovery.smiles,
          confidenceScore: discovery.confidence_score,
          safetyScore: discovery.safety_score,
          efficacyScore: discovery.efficacy_score,
          similarityScore: discovery.similarity_score,
          drugLikenessScore: 100, // Default for autonomous discoveries
          patentStatus: discovery.patent_status === "Patent-Free" ? "patent-free" : "patent-opportunity",
          marketValue: discovery.market_value,
          therapeuticPotential: discovery.therapeutic_potential,
          keyDifferences: discovery.key_differences,
          discoveredBy: "autonomous_research_engine",
          discoveredAt: new Date(discovery.discovered_at),
        });

        importedCount++;
      } catch (error) {
        console.error(`Failed to import discovery ${discovery.compound_id}:`, error);
      }
    }

    return {
      success: true,
      importedCount,
    };
  } catch (error: any) {
    if (error.code === "ENOENT") {
      console.log("No autonomous discoveries file found at:", DISCOVERIES_PATH);
      return {
        success: true,
        importedCount: 0,
      };
    }

    return {
      success: false,
      importedCount: 0,
      error: error.message,
    };
  }
}
