import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { getDb } from "./db";
import { analogDiscoveries } from "../drizzle/schema";
import { eq } from "drizzle-orm";
import { existsSync, readFile as readFileCallback } from "fs";
import { promisify } from "util";
import { executePythonScriptSafe } from "./_core/pythonBridgeSafe";

const readFile = promisify(readFileCallback);;

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Import autonomous discoveries from pharmasight-platform
 * Reads from the autonomous_discoveries.json file generated by the research engine
 */

const DISCOVERIES_PATH = "/home/ubuntu/pharmasight-admin-dashboard/data/autonomous_research_output.json";

interface AutonomousDiscovery {
  compound_id: string;
  compound_name: string;
  parent_compound: string;
  smiles: string;
  confidence_score: number;
  safety_score: number;
  efficacy_score: number;
  similarity_score: number;
  patent_status: string;
  market_value: string;
  therapeutic_potential: string;
  key_differences: string;
  discovered_at: string;
}

/**
 * Apply diversity filtering to discoveries using Python diversity_filter module
 */
async function applyDiversityFiltering(discoveries: any[], existingSmiles: string[]): Promise<any[]> {
  try {
    // Use safe wrapper - will return original if Python unavailable
    const result = await executePythonScriptSafe("diversity_filter.py", "filter_discoveries_from_json", [
      discoveries,
      existingSmiles,
      0.3, // min_threshold
    ]);

    if (typeof result === 'object' && result !== null && 'filtered' in result) {
      const filtered = (result as any).filtered;
      console.log(`[Diversity Filter] Filtered ${discoveries.length} → ${filtered.length} discoveries`);
      return filtered;
    }

    // Fallback: return original if filtering unavailable
    console.log("[Diversity Filter] Python unavailable, returning original discoveries");
    return discoveries;
  } catch (error) {
    console.error("[Diversity Filter] Error:", error);
    return discoveries; // Return original on error
  }
}

export async function importAutonomousDiscoveries(): Promise<{
  success: boolean;
  importedCount: number;
  error?: string;
}> {
  try {
    // Read the autonomous discoveries file
    const fileContent = await readFile(DISCOVERIES_PATH, "utf-8");
    let discoveries: AutonomousDiscovery[] = JSON.parse(fileContent);

    if (!Array.isArray(discoveries) || discoveries.length === 0) {
      return {
        success: true,
        importedCount: 0,
      };
    }

    const db = await getDb();
    if (!db) {
      return {
        success: false,
        importedCount: 0,
        error: "Database not available",
      };
    }
    
    // Get existing SMILES from database for diversity filtering
    const existingAnalogs = await db.select({ smiles: analogDiscoveries.smiles }).from(analogDiscoveries);
    const existingSmiles = existingAnalogs.map(a => a.smiles);
    
    // Apply diversity filtering
    console.log(`[Import] Applying diversity filter to ${discoveries.length} discoveries...`);
    discoveries = await applyDiversityFiltering(discoveries, existingSmiles) as any[];

    let importedCount = 0;

    // Import each discovery
    for (const discovery of discoveries as any[]) {
      try {
        // Check if already exists
        const existing = await db
          .select()
          .from(analogDiscoveries)
          .where(eq(analogDiscoveries.compoundId, discovery.compound_id))
          .limit(1);

        if (existing.length > 0) {
          continue; // Skip if already imported
        }

        // Insert new discovery (map Python format to DB schema)
        await db.insert(analogDiscoveries).values({
          compoundId: discovery.discovery_id || `AUTO-${Date.now()}`,
          compoundName: discovery.compound_name,
          parentCompound: discovery.therapeutic_area || "Unknown",
          smiles: discovery.compound_smiles,
          confidenceScore: discovery.confidence || 0,
          safetyScore: 85, // Default for autonomous discoveries
          efficacyScore: 85, // Default for autonomous discoveries
          similarityScore: 85, // Default (int 0-100)
          drugLikenessScore: 100,
          patentStatus: discovery.key_features?.includes("Patent-free") ? "patent-free" : "patent-opportunity",
          marketValue: discovery.estimated_value || 0,
          therapeuticPotential: discovery.mechanism || "Unknown",
          keyDifferences: discovery.key_features?.join(", ") || "",
          discoveredBy: "autonomous_system",
          discoveredAt: new Date(discovery.timestamp),
        });

        importedCount++;
      } catch (error) {
        console.error(`Failed to import discovery ${discovery.compound_id}:`, error);
      }
    }

    return {
      success: true,
      importedCount,
    };
  } catch (error: any) {
    if (error.code === "ENOENT") {
      console.log("No autonomous discoveries file found at:", DISCOVERIES_PATH);
      return {
        success: true,
        importedCount: 0,
      };
    }

    return {
      success: false,
      importedCount: 0,
      error: error.message,
    };
  }
}
